version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: rust-async-graphql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
      TZ: Asia/Tokyo
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --default-authentication-plugin=mysql_native_password,
      ]
    ports:
      - "33063:3306"